version: '3'

services:

    solid-php-app:
        build: .
        container_name: solid-php-app
        #entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
        ports: 
            - "3000:3000"
        volumes:
            - .:/var/www
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
