version: '3'

services:

    solid-php-app:
        build: .
        container_name: solid-php-app
        #entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
        ports: 
            - "3000:3000"
        volumes:
            - .:/var/www
        networks:
            - app-network

    solid-php-db:
        build: ./.docker/mysql
        container_name: solid-php-db
        #restart: always
        tty: true
        ports:
            - "33007:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=test
            - MYSQL_ROOT_PASSWORD=root
            #- MYSQL_USER=root
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
